<?xml version="1.0" encoding="utf-8"?><Database Name="Seed" Class="ItemsEditDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=Seed;Integrated Security=True" SettingsObjectName="SeedApp.My.MySettings" SettingsPropertyName="SeedConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="Item" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Lot" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[PLS%]" Member="PLS_" Type="System.Decimal" DbType="Decimal(20,10)" CanBeNull="true" />
      <Column Name="variety" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Purity" Type="System.Decimal" DbType="Decimal(20,10)" CanBeNull="true" />
      <Column Name="Crop" Type="System.Decimal" DbType="Decimal(20,10)" CanBeNull="true" />
      <Column Name="Weeds" Type="System.Decimal" DbType="Decimal(20,10)" CanBeNull="true" />
      <Column Name="Germ" Type="System.Decimal" DbType="Decimal(20,10)" CanBeNull="true" />
      <Column Name="Dormant" Type="System.Decimal" DbType="Decimal(20,10)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,10)" CanBeNull="true" />
      <Column Name="[Test Date]" Member="Test_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Orgin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Distributor" Type="System.Decimal" DbType="Decimal(12,4)" CanBeNull="true" />
      <Column Name="Wholesale" Type="System.Decimal" DbType="Decimal(12,4)" CanBeNull="true" />
      <Column Name="Retail" Type="System.Decimal" DbType="Decimal(12,4)" CanBeNull="true" />
      <Column Name="Item1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Item2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ReorderQTY" Type="System.Decimal" DbType="Decimal(12,4)" CanBeNull="true" />
      <Column Name="Reorder" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Discontinued" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ScientificName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>