'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Seed")>  _
Partial Public Class SeedReportsDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.SeedApp.My.MySettings.Default.SeedConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property SeedReports() As System.Data.Linq.Table(Of SeedReport)
		Get
			Return Me.GetTable(Of SeedReport)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Reports")>  _
Partial Public Class SeedReport
	
	Private _ReportFileName As String
	
	Private _FriendlyName As String
	
	Private _ReportID As System.Nullable(Of Long)
	
	Private _HasSubReports As System.Nullable(Of Boolean)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ReportFileName", DbType:="NVarChar(100)")>  _
	Public Property ReportFileName() As String
		Get
			Return Me._ReportFileName
		End Get
		Set
			If (String.Equals(Me._ReportFileName, value) = false) Then
				Me._ReportFileName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FriendlyName", DbType:="NVarChar(100)")>  _
	Public Property FriendlyName() As String
		Get
			Return Me._FriendlyName
		End Get
		Set
			If (String.Equals(Me._FriendlyName, value) = false) Then
				Me._FriendlyName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ReportID", DbType:="BigInt")>  _
	Public Property ReportID() As System.Nullable(Of Long)
		Get
			Return Me._ReportID
		End Get
		Set
			If (Me._ReportID.Equals(value) = false) Then
				Me._ReportID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HasSubReports", DbType:="Bit")>  _
	Public Property HasSubReports() As System.Nullable(Of Boolean)
		Get
			Return Me._HasSubReports
		End Get
		Set
			If (Me._HasSubReports.Equals(value) = false) Then
				Me._HasSubReports = value
			End If
		End Set
	End Property
End Class
