<?xml version="1.0" encoding="utf-8"?><Database Name="Seed" Class="CustomersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CustomerAddressLine1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CustomerAddressLine2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CustomerCity" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CustomerState" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CustomerZip" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="QBId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomerPhone" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>