'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Seed")>  _
Partial Public Class NetWeightDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertNetWeight(instance As NetWeight)
    End Sub
  Partial Private Sub UpdateNetWeight(instance As NetWeight)
    End Sub
  Partial Private Sub DeleteNetWeight(instance As NetWeight)
    End Sub
#End Region
    Public Sub New()
        MyBase.New(Global.SeedGeneral.My.MySettings.Default.SeedConnectionString, mappingSource)
        OnCreated()
    End Sub
    Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property NetWeights() As System.Data.Linq.Table(Of NetWeight)
		Get
			Return Me.GetTable(Of NetWeight)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.NetWeight")>  _
Partial Public Class NetWeight
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _NetWtID As Integer
	
	Private _NetWtDescription As String
	
	Private _IsDefault As System.Nullable(Of Boolean)
	
	Private _DefaultPages As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnNetWtIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnNetWtIDChanged()
    End Sub
    Partial Private Sub OnNetWtDescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnNetWtDescriptionChanged()
    End Sub
    Partial Private Sub OnIsDefaultChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsDefaultChanged()
    End Sub
    Partial Private Sub OnDefaultPagesChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnDefaultPagesChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NetWtID", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property NetWtID() As Integer
		Get
			Return Me._NetWtID
		End Get
		Set
			If ((Me._NetWtID = value)  _
						= false) Then
				Me.OnNetWtIDChanging(value)
				Me.SendPropertyChanging
				Me._NetWtID = value
				Me.SendPropertyChanged("NetWtID")
				Me.OnNetWtIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NetWtDescription", DbType:="NVarChar(100)")>  _
	Public Property NetWtDescription() As String
		Get
			Return Me._NetWtDescription
		End Get
		Set
			If (String.Equals(Me._NetWtDescription, value) = false) Then
				Me.OnNetWtDescriptionChanging(value)
				Me.SendPropertyChanging
				Me._NetWtDescription = value
				Me.SendPropertyChanged("NetWtDescription")
				Me.OnNetWtDescriptionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsDefault", DbType:="Bit")>  _
	Public Property IsDefault() As System.Nullable(Of Boolean)
		Get
			Return Me._IsDefault
		End Get
		Set
			If (Me._IsDefault.Equals(value) = false) Then
				Me.OnIsDefaultChanging(value)
				Me.SendPropertyChanging
				Me._IsDefault = value
				Me.SendPropertyChanged("IsDefault")
				Me.OnIsDefaultChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DefaultPages", DbType:="Int")>  _
	Public Property DefaultPages() As System.Nullable(Of Integer)
		Get
			Return Me._DefaultPages
		End Get
		Set
			If (Me._DefaultPages.Equals(value) = false) Then
				Me.OnDefaultPagesChanging(value)
				Me.SendPropertyChanging
				Me._DefaultPages = value
				Me.SendPropertyChanged("DefaultPages")
				Me.OnDefaultPagesChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
