'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Seed")>  _
Partial Public Class OrderItemsDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertOrderCustomerDetails(instance As OrderCustomerDetails)
    End Sub
  Partial Private Sub UpdateOrderCustomerDetails(instance As OrderCustomerDetails)
    End Sub
  Partial Private Sub DeleteOrderCustomerDetails(instance As OrderCustomerDetails)
    End Sub
  Partial Private Sub InsertOrderItemDetail(instance As OrderItemDetail)
    End Sub
  Partial Private Sub UpdateOrderItemDetail(instance As OrderItemDetail)
    End Sub
  Partial Private Sub DeleteOrderItemDetail(instance As OrderItemDetail)
    End Sub
  Partial Private Sub InsertOrder(instance As [Order])
    End Sub
  Partial Private Sub UpdateOrder(instance As [Order])
    End Sub
  Partial Private Sub DeleteOrder(instance As [Order])
    End Sub
  Partial Private Sub InsertOrderItem(instance As OrderItem)
    End Sub
  Partial Private Sub UpdateOrderItem(instance As OrderItem)
    End Sub
  Partial Private Sub DeleteOrderItem(instance As OrderItem)
    End Sub
#End Region
    Public Sub New()
        MyBase.New(My.MySettings.Default.SeedConnectionString, mappingSource)
        OnCreated()
    End Sub
    Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property OrderStatusDetails() As System.Data.Linq.Table(Of OrderStatusDetail)
		Get
			Return Me.GetTable(Of OrderStatusDetail)
		End Get
	End Property
	
	Public ReadOnly Property OrderCustomerDetails() As System.Data.Linq.Table(Of OrderCustomerDetails)
		Get
			Return Me.GetTable(Of OrderCustomerDetails)
		End Get
	End Property
	
	Public ReadOnly Property OrderItemDetails() As System.Data.Linq.Table(Of OrderItemDetail)
		Get
			Return Me.GetTable(Of OrderItemDetail)
		End Get
	End Property
	
	Public ReadOnly Property Orders() As System.Data.Linq.Table(Of [Order])
		Get
			Return Me.GetTable(Of [Order])
		End Get
	End Property
	
	Public ReadOnly Property OrderItems() As System.Data.Linq.Table(Of OrderItem)
		Get
			Return Me.GetTable(Of OrderItem)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.OrderStatus")>  _
Partial Public Class OrderStatusDetail
	
	Private _OrderStatusID As System.Nullable(Of Long)
	
	Private _OrderStatusName As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderStatusID", DbType:="BigInt")>  _
	Public Property OrderStatusID() As System.Nullable(Of Long)
		Get
			Return Me._OrderStatusID
		End Get
		Set
			If (Me._OrderStatusID.Equals(value) = false) Then
				Me._OrderStatusID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderStatusName", DbType:="NVarChar(50)")>  _
	Public Property OrderStatusName() As String
		Get
			Return Me._OrderStatusName
		End Get
		Set
			If (String.Equals(Me._OrderStatusName, value) = false) Then
				Me._OrderStatusName = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Customers")>  _
Partial Public Class OrderCustomerDetails
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _CustomerId As Integer
	
	Private _CustomerName As String
	
	Private _CustomerAddressLine1 As String
	
	Private _CustomerAddressLine2 As String
	
	Private _CustomerCity As String
	
	Private _CustomerState As String
	
	Private _CustomerZip As String
	
	Private _QBId As String
	
	Private _Order As EntityRef(Of [Order])
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnCustomerIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnCustomerIdChanged()
    End Sub
    Partial Private Sub OnCustomerNameChanging(value As String)
    End Sub
    Partial Private Sub OnCustomerNameChanged()
    End Sub
    Partial Private Sub OnCustomerAddressLine1Changing(value As String)
    End Sub
    Partial Private Sub OnCustomerAddressLine1Changed()
    End Sub
    Partial Private Sub OnCustomerAddressLine2Changing(value As String)
    End Sub
    Partial Private Sub OnCustomerAddressLine2Changed()
    End Sub
    Partial Private Sub OnCustomerCityChanging(value As String)
    End Sub
    Partial Private Sub OnCustomerCityChanged()
    End Sub
    Partial Private Sub OnCustomerStateChanging(value As String)
    End Sub
    Partial Private Sub OnCustomerStateChanged()
    End Sub
    Partial Private Sub OnCustomerZipChanging(value As String)
    End Sub
    Partial Private Sub OnCustomerZipChanged()
    End Sub
    Partial Private Sub OnQBIdChanging(value As String)
    End Sub
    Partial Private Sub OnQBIdChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._Order = CType(Nothing, EntityRef(Of [Order]))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerId", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property CustomerId() As Integer
		Get
			Return Me._CustomerId
		End Get
		Set
			If ((Me._CustomerId = value)  _
						= false) Then
				If Me._Order.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnCustomerIdChanging(value)
				Me.SendPropertyChanging
				Me._CustomerId = value
				Me.SendPropertyChanged("CustomerId")
				Me.OnCustomerIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerName", DbType:="NVarChar(255)")>  _
	Public Property CustomerName() As String
		Get
			Return Me._CustomerName
		End Get
		Set
			If (String.Equals(Me._CustomerName, value) = false) Then
				Me.OnCustomerNameChanging(value)
				Me.SendPropertyChanging
				Me._CustomerName = value
				Me.SendPropertyChanged("CustomerName")
				Me.OnCustomerNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerAddressLine1", DbType:="NVarChar(255)")>  _
	Public Property CustomerAddressLine1() As String
		Get
			Return Me._CustomerAddressLine1
		End Get
		Set
			If (String.Equals(Me._CustomerAddressLine1, value) = false) Then
				Me.OnCustomerAddressLine1Changing(value)
				Me.SendPropertyChanging
				Me._CustomerAddressLine1 = value
				Me.SendPropertyChanged("CustomerAddressLine1")
				Me.OnCustomerAddressLine1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerAddressLine2", DbType:="NVarChar(255)")>  _
	Public Property CustomerAddressLine2() As String
		Get
			Return Me._CustomerAddressLine2
		End Get
		Set
			If (String.Equals(Me._CustomerAddressLine2, value) = false) Then
				Me.OnCustomerAddressLine2Changing(value)
				Me.SendPropertyChanging
				Me._CustomerAddressLine2 = value
				Me.SendPropertyChanged("CustomerAddressLine2")
				Me.OnCustomerAddressLine2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerCity", DbType:="NVarChar(100)")>  _
	Public Property CustomerCity() As String
		Get
			Return Me._CustomerCity
		End Get
		Set
			If (String.Equals(Me._CustomerCity, value) = false) Then
				Me.OnCustomerCityChanging(value)
				Me.SendPropertyChanging
				Me._CustomerCity = value
				Me.SendPropertyChanged("CustomerCity")
				Me.OnCustomerCityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerState", DbType:="NVarChar(10)")>  _
	Public Property CustomerState() As String
		Get
			Return Me._CustomerState
		End Get
		Set
			If (String.Equals(Me._CustomerState, value) = false) Then
				Me.OnCustomerStateChanging(value)
				Me.SendPropertyChanging
				Me._CustomerState = value
				Me.SendPropertyChanged("CustomerState")
				Me.OnCustomerStateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerZip", DbType:="NVarChar(10)")>  _
	Public Property CustomerZip() As String
		Get
			Return Me._CustomerZip
		End Get
		Set
			If (String.Equals(Me._CustomerZip, value) = false) Then
				Me.OnCustomerZipChanging(value)
				Me.SendPropertyChanging
				Me._CustomerZip = value
				Me.SendPropertyChanged("CustomerZip")
				Me.OnCustomerZipChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_QBId", DbType:="NVarChar(MAX)")>  _
	Public Property QBId() As String
		Get
			Return Me._QBId
		End Get
		Set
			If (String.Equals(Me._QBId, value) = false) Then
				Me.OnQBIdChanging(value)
				Me.SendPropertyChanging
				Me._QBId = value
				Me.SendPropertyChanged("QBId")
				Me.OnQBIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="Order_OrderCustomerDetails", Storage:="_Order", ThisKey:="CustomerId", OtherKey:="CustomerID", IsForeignKey:=true)>  _
	Public Property [Order]() As [Order]
		Get
			Return Me._Order.Entity
		End Get
		Set
			Dim previousValue As [Order] = Me._Order.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._Order.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._Order.Entity = Nothing
					previousValue.OrderCustomerDetails.Remove(Me)
				End If
				Me._Order.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.OrderCustomerDetails.Add(Me)
					Me._CustomerId = value.CustomerID
				Else
					Me._CustomerId = CType(Nothing, Integer)
				End If
				Me.SendPropertyChanged("[Order]")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Items")>  _
Partial Public Class OrderItemDetail
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Item As String
	
	Private _Lot As String
	
	Private _PLS_ As System.Nullable(Of Decimal)
	
	Private _variety As String
	
	Private _Purity As System.Nullable(Of Decimal)
	
	Private _Crop As System.Nullable(Of Decimal)
	
	Private _Weeds As System.Nullable(Of Decimal)
	
	Private _Germ As System.Nullable(Of Decimal)
	
	Private _Dormant As System.Nullable(Of Decimal)
	
	Private _Total As System.Nullable(Of Decimal)
	
	Private _Test_Date As System.Nullable(Of Date)
	
	Private _Orgin As String
	
	Private _Distributor As System.Nullable(Of Decimal)
	
	Private _Wholesale As System.Nullable(Of Decimal)
	
	Private _Retail As System.Nullable(Of Decimal)
	
	Private _Item1 As String
	
	Private _Item2 As String
	
	Private _ReorderQTY As System.Nullable(Of Decimal)
	
	Private _Reorder As System.Nullable(Of Boolean)
	
	Private _Discontinued As System.Nullable(Of Boolean)
	
	Private _ScientificName As String
	
	Private _ItemID As Integer
	
	Private _Type As String
	
	Private _Inert As System.Nullable(Of Decimal)
	
	Private _OrderItem As EntityRef(Of OrderItem)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnItemChanging(value As String)
    End Sub
    Partial Private Sub OnItemChanged()
    End Sub
    Partial Private Sub OnLotChanging(value As String)
    End Sub
    Partial Private Sub OnLotChanged()
    End Sub
    Partial Private Sub OnPLS_Changing(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnPLS_Changed()
    End Sub
    Partial Private Sub OnvarietyChanging(value As String)
    End Sub
    Partial Private Sub OnvarietyChanged()
    End Sub
    Partial Private Sub OnPurityChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnPurityChanged()
    End Sub
    Partial Private Sub OnCropChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnCropChanged()
    End Sub
    Partial Private Sub OnWeedsChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnWeedsChanged()
    End Sub
    Partial Private Sub OnGermChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnGermChanged()
    End Sub
    Partial Private Sub OnDormantChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnDormantChanged()
    End Sub
    Partial Private Sub OnTotalChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnTotalChanged()
    End Sub
    Partial Private Sub OnTest_DateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnTest_DateChanged()
    End Sub
    Partial Private Sub OnOrginChanging(value As String)
    End Sub
    Partial Private Sub OnOrginChanged()
    End Sub
    Partial Private Sub OnDistributorChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnDistributorChanged()
    End Sub
    Partial Private Sub OnWholesaleChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnWholesaleChanged()
    End Sub
    Partial Private Sub OnRetailChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnRetailChanged()
    End Sub
    Partial Private Sub OnItem1Changing(value As String)
    End Sub
    Partial Private Sub OnItem1Changed()
    End Sub
    Partial Private Sub OnItem2Changing(value As String)
    End Sub
    Partial Private Sub OnItem2Changed()
    End Sub
    Partial Private Sub OnReorderQTYChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnReorderQTYChanged()
    End Sub
    Partial Private Sub OnReorderChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnReorderChanged()
    End Sub
    Partial Private Sub OnDiscontinuedChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnDiscontinuedChanged()
    End Sub
    Partial Private Sub OnScientificNameChanging(value As String)
    End Sub
    Partial Private Sub OnScientificNameChanged()
    End Sub
    Partial Private Sub OnItemIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnItemIDChanged()
    End Sub
    Partial Private Sub OnTypeChanging(value As String)
    End Sub
    Partial Private Sub OnTypeChanged()
    End Sub
    Partial Private Sub OnInertChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnInertChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._OrderItem = CType(Nothing, EntityRef(Of OrderItem))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item", DbType:="NVarChar(100)")>  _
	Public Property Item() As String
		Get
			Return Me._Item
		End Get
		Set
			If (String.Equals(Me._Item, value) = false) Then
				Me.OnItemChanging(value)
				Me.SendPropertyChanging
				Me._Item = value
				Me.SendPropertyChanged("Item")
				Me.OnItemChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Lot", DbType:="NVarChar(100)")>  _
	Public Property Lot() As String
		Get
			Return Me._Lot
		End Get
		Set
			If (String.Equals(Me._Lot, value) = false) Then
				Me.OnLotChanging(value)
				Me.SendPropertyChanging
				Me._Lot = value
				Me.SendPropertyChanged("Lot")
				Me.OnLotChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[PLS%]", Storage:="_PLS_", DbType:="Decimal(20,10)")>  _
	Public Property PLS_() As System.Nullable(Of Decimal)
		Get
			Return Me._PLS_
		End Get
		Set
			If (Me._PLS_.Equals(value) = false) Then
				Me.OnPLS_Changing(value)
				Me.SendPropertyChanging
				Me._PLS_ = value
				Me.SendPropertyChanged("PLS_")
				Me.OnPLS_Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_variety", DbType:="NVarChar(100)")>  _
	Public Property variety() As String
		Get
			Return Me._variety
		End Get
		Set
			If (String.Equals(Me._variety, value) = false) Then
				Me.OnvarietyChanging(value)
				Me.SendPropertyChanging
				Me._variety = value
				Me.SendPropertyChanged("variety")
				Me.OnvarietyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Purity", DbType:="Decimal(20,10)")>  _
	Public Property Purity() As System.Nullable(Of Decimal)
		Get
			Return Me._Purity
		End Get
		Set
			If (Me._Purity.Equals(value) = false) Then
				Me.OnPurityChanging(value)
				Me.SendPropertyChanging
				Me._Purity = value
				Me.SendPropertyChanged("Purity")
				Me.OnPurityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Crop", DbType:="Decimal(20,10)")>  _
	Public Property Crop() As System.Nullable(Of Decimal)
		Get
			Return Me._Crop
		End Get
		Set
			If (Me._Crop.Equals(value) = false) Then
				Me.OnCropChanging(value)
				Me.SendPropertyChanging
				Me._Crop = value
				Me.SendPropertyChanged("Crop")
				Me.OnCropChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Weeds", DbType:="Decimal(20,10)")>  _
	Public Property Weeds() As System.Nullable(Of Decimal)
		Get
			Return Me._Weeds
		End Get
		Set
			If (Me._Weeds.Equals(value) = false) Then
				Me.OnWeedsChanging(value)
				Me.SendPropertyChanging
				Me._Weeds = value
				Me.SendPropertyChanged("Weeds")
				Me.OnWeedsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Germ", DbType:="Decimal(20,10)")>  _
	Public Property Germ() As System.Nullable(Of Decimal)
		Get
			Return Me._Germ
		End Get
		Set
			If (Me._Germ.Equals(value) = false) Then
				Me.OnGermChanging(value)
				Me.SendPropertyChanging
				Me._Germ = value
				Me.SendPropertyChanged("Germ")
				Me.OnGermChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Dormant", DbType:="Decimal(20,10)")>  _
	Public Property Dormant() As System.Nullable(Of Decimal)
		Get
			Return Me._Dormant
		End Get
		Set
			If (Me._Dormant.Equals(value) = false) Then
				Me.OnDormantChanging(value)
				Me.SendPropertyChanging
				Me._Dormant = value
				Me.SendPropertyChanged("Dormant")
				Me.OnDormantChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Total", DbType:="Decimal(20,10)")>  _
	Public Property Total() As System.Nullable(Of Decimal)
		Get
			Return Me._Total
		End Get
		Set
			If (Me._Total.Equals(value) = false) Then
				Me.OnTotalChanging(value)
				Me.SendPropertyChanging
				Me._Total = value
				Me.SendPropertyChanged("Total")
				Me.OnTotalChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Test Date]", Storage:="_Test_Date", DbType:="DateTime")>  _
	Public Property Test_Date() As System.Nullable(Of Date)
		Get
			Return Me._Test_Date
		End Get
		Set
			If (Me._Test_Date.Equals(value) = false) Then
				Me.OnTest_DateChanging(value)
				Me.SendPropertyChanging
				Me._Test_Date = value
				Me.SendPropertyChanged("Test_Date")
				Me.OnTest_DateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Orgin", DbType:="NVarChar(100)")>  _
	Public Property Orgin() As String
		Get
			Return Me._Orgin
		End Get
		Set
			If (String.Equals(Me._Orgin, value) = false) Then
				Me.OnOrginChanging(value)
				Me.SendPropertyChanging
				Me._Orgin = value
				Me.SendPropertyChanged("Orgin")
				Me.OnOrginChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Distributor", DbType:="Decimal(12,4)")>  _
	Public Property Distributor() As System.Nullable(Of Decimal)
		Get
			Return Me._Distributor
		End Get
		Set
			If (Me._Distributor.Equals(value) = false) Then
				Me.OnDistributorChanging(value)
				Me.SendPropertyChanging
				Me._Distributor = value
				Me.SendPropertyChanged("Distributor")
				Me.OnDistributorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Wholesale", DbType:="Decimal(12,4)")>  _
	Public Property Wholesale() As System.Nullable(Of Decimal)
		Get
			Return Me._Wholesale
		End Get
		Set
			If (Me._Wholesale.Equals(value) = false) Then
				Me.OnWholesaleChanging(value)
				Me.SendPropertyChanging
				Me._Wholesale = value
				Me.SendPropertyChanged("Wholesale")
				Me.OnWholesaleChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Retail", DbType:="Decimal(12,4)")>  _
	Public Property Retail() As System.Nullable(Of Decimal)
		Get
			Return Me._Retail
		End Get
		Set
			If (Me._Retail.Equals(value) = false) Then
				Me.OnRetailChanging(value)
				Me.SendPropertyChanging
				Me._Retail = value
				Me.SendPropertyChanged("Retail")
				Me.OnRetailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item1", DbType:="NVarChar(100)")>  _
	Public Property Item1() As String
		Get
			Return Me._Item1
		End Get
		Set
			If (String.Equals(Me._Item1, value) = false) Then
				Me.OnItem1Changing(value)
				Me.SendPropertyChanging
				Me._Item1 = value
				Me.SendPropertyChanged("Item1")
				Me.OnItem1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item2", DbType:="NVarChar(100)")>  _
	Public Property Item2() As String
		Get
			Return Me._Item2
		End Get
		Set
			If (String.Equals(Me._Item2, value) = false) Then
				Me.OnItem2Changing(value)
				Me.SendPropertyChanging
				Me._Item2 = value
				Me.SendPropertyChanged("Item2")
				Me.OnItem2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ReorderQTY", DbType:="Decimal(12,4)")>  _
	Public Property ReorderQTY() As System.Nullable(Of Decimal)
		Get
			Return Me._ReorderQTY
		End Get
		Set
			If (Me._ReorderQTY.Equals(value) = false) Then
				Me.OnReorderQTYChanging(value)
				Me.SendPropertyChanging
				Me._ReorderQTY = value
				Me.SendPropertyChanged("ReorderQTY")
				Me.OnReorderQTYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reorder", DbType:="Bit")>  _
	Public Property Reorder() As System.Nullable(Of Boolean)
		Get
			Return Me._Reorder
		End Get
		Set
			If (Me._Reorder.Equals(value) = false) Then
				Me.OnReorderChanging(value)
				Me.SendPropertyChanging
				Me._Reorder = value
				Me.SendPropertyChanged("Reorder")
				Me.OnReorderChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Discontinued", DbType:="Bit")>  _
	Public Property Discontinued() As System.Nullable(Of Boolean)
		Get
			Return Me._Discontinued
		End Get
		Set
			If (Me._Discontinued.Equals(value) = false) Then
				Me.OnDiscontinuedChanging(value)
				Me.SendPropertyChanging
				Me._Discontinued = value
				Me.SendPropertyChanged("Discontinued")
				Me.OnDiscontinuedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ScientificName", DbType:="VarChar(255)")>  _
	Public Property ScientificName() As String
		Get
			Return Me._ScientificName
		End Get
		Set
			If (String.Equals(Me._ScientificName, value) = false) Then
				Me.OnScientificNameChanging(value)
				Me.SendPropertyChanging
				Me._ScientificName = value
				Me.SendPropertyChanged("ScientificName")
				Me.OnScientificNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ItemID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ItemID() As Integer
		Get
			Return Me._ItemID
		End Get
		Set
			If ((Me._ItemID = value)  _
						= false) Then
				If Me._OrderItem.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnItemIDChanging(value)
				Me.SendPropertyChanging
				Me._ItemID = value
				Me.SendPropertyChanged("ItemID")
				Me.OnItemIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Type", DbType:="NVarChar(50)")>  _
	Public Property Type() As String
		Get
			Return Me._Type
		End Get
		Set
			If (String.Equals(Me._Type, value) = false) Then
				Me.OnTypeChanging(value)
				Me.SendPropertyChanging
				Me._Type = value
				Me.SendPropertyChanged("Type")
				Me.OnTypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Inert", DbType:="Decimal(12,4)")>  _
	Public Property Inert() As System.Nullable(Of Decimal)
		Get
			Return Me._Inert
		End Get
		Set
			If (Me._Inert.Equals(value) = false) Then
				Me.OnInertChanging(value)
				Me.SendPropertyChanging
				Me._Inert = value
				Me.SendPropertyChanged("Inert")
				Me.OnInertChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="OrderItem_OrderItemDetail", Storage:="_OrderItem", ThisKey:="ItemID", OtherKey:="ItemID", IsForeignKey:=true)>  _
	Public Property OrderItem() As OrderItem
		Get
			Return Me._OrderItem.Entity
		End Get
		Set
			Dim previousValue As OrderItem = Me._OrderItem.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._OrderItem.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._OrderItem.Entity = Nothing
					previousValue.OrderItemDetails.Remove(Me)
				End If
				Me._OrderItem.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.OrderItemDetails.Add(Me)
					Me._ItemID = value.ItemID
				Else
					Me._ItemID = CType(Nothing, Integer)
				End If
				Me.SendPropertyChanged("OrderItem")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Orders")>  _
Partial Public Class [Order]
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _OrderID As Integer
	
	Private _InvoiceID As String
	
	Private _CustomerID As Integer
	
	Private _Project As String
	
	Private _Acres As System.Nullable(Of Decimal)
	
	Private _OrderTotal As System.Nullable(Of Decimal)
	
	Private _OrderDate As System.Nullable(Of Date)
	
	Private _SubmittedBy As String
	
	Private _TotalPricePerAcre As System.Nullable(Of Decimal)
	
	Private _OrderStatusId As System.Nullable(Of Long)
	
	Private _PriceList As String
	
	Private _OrderCustomerDetails As EntitySet(Of OrderCustomerDetails)
	
	Private _OrderItems As EntitySet(Of OrderItem)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnOrderIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnOrderIDChanged()
    End Sub
    Partial Private Sub OnInvoiceIDChanging(value As String)
    End Sub
    Partial Private Sub OnInvoiceIDChanged()
    End Sub
    Partial Private Sub OnCustomerIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnCustomerIDChanged()
    End Sub
    Partial Private Sub OnProjectChanging(value As String)
    End Sub
    Partial Private Sub OnProjectChanged()
    End Sub
    Partial Private Sub OnAcresChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnAcresChanged()
    End Sub
    Partial Private Sub OnOrderTotalChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnOrderTotalChanged()
    End Sub
    Partial Private Sub OnOrderDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnOrderDateChanged()
    End Sub
    Partial Private Sub OnSubmittedByChanging(value As String)
    End Sub
    Partial Private Sub OnSubmittedByChanged()
    End Sub
    Partial Private Sub OnTotalPricePerAcreChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnTotalPricePerAcreChanged()
    End Sub
    Partial Private Sub OnOrderStatusIdChanging(value As System.Nullable(Of Long))
    End Sub
    Partial Private Sub OnOrderStatusIdChanged()
    End Sub
    Partial Private Sub OnPriceListChanging(value As String)
    End Sub
    Partial Private Sub OnPriceListChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._OrderCustomerDetails = New EntitySet(Of OrderCustomerDetails)(AddressOf Me.attach_OrderCustomerDetails, AddressOf Me.detach_OrderCustomerDetails)
		Me._OrderItems = New EntitySet(Of OrderItem)(AddressOf Me.attach_OrderItems, AddressOf Me.detach_OrderItems)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property OrderID() As Integer
		Get
			Return Me._OrderID
		End Get
		Set
			If ((Me._OrderID = value)  _
						= false) Then
				Me.OnOrderIDChanging(value)
				Me.SendPropertyChanging
				Me._OrderID = value
				Me.SendPropertyChanged("OrderID")
				Me.OnOrderIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InvoiceID", DbType:="NVarChar(50)")>  _
	Public Property InvoiceID() As String
		Get
			Return Me._InvoiceID
		End Get
		Set
			If (String.Equals(Me._InvoiceID, value) = false) Then
				Me.OnInvoiceIDChanging(value)
				Me.SendPropertyChanging
				Me._InvoiceID = value
				Me.SendPropertyChanged("InvoiceID")
				Me.OnInvoiceIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerID", DbType:="Int NOT NULL")>  _
	Public Property CustomerID() As Integer
		Get
			Return Me._CustomerID
		End Get
		Set
			If ((Me._CustomerID = value)  _
						= false) Then
				Me.OnCustomerIDChanging(value)
				Me.SendPropertyChanging
				Me._CustomerID = value
				Me.SendPropertyChanged("CustomerID")
				Me.OnCustomerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Project", DbType:="NVarChar(100)")>  _
	Public Property Project() As String
		Get
			Return Me._Project
		End Get
		Set
			If (String.Equals(Me._Project, value) = false) Then
				Me.OnProjectChanging(value)
				Me.SendPropertyChanging
				Me._Project = value
				Me.SendPropertyChanged("Project")
				Me.OnProjectChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Acres", DbType:="Decimal(12,2)")>  _
	Public Property Acres() As System.Nullable(Of Decimal)
		Get
			Return Me._Acres
		End Get
		Set
			If (Me._Acres.Equals(value) = false) Then
				Me.OnAcresChanging(value)
				Me.SendPropertyChanging
				Me._Acres = value
				Me.SendPropertyChanged("Acres")
				Me.OnAcresChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderTotal", DbType:="Decimal(12,4)")>  _
	Public Property OrderTotal() As System.Nullable(Of Decimal)
		Get
			Return Me._OrderTotal
		End Get
		Set
			If (Me._OrderTotal.Equals(value) = false) Then
				Me.OnOrderTotalChanging(value)
				Me.SendPropertyChanging
				Me._OrderTotal = value
				Me.SendPropertyChanged("OrderTotal")
				Me.OnOrderTotalChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderDate", DbType:="DateTime")>  _
	Public Property OrderDate() As System.Nullable(Of Date)
		Get
			Return Me._OrderDate
		End Get
		Set
			If (Me._OrderDate.Equals(value) = false) Then
				Me.OnOrderDateChanging(value)
				Me.SendPropertyChanging
				Me._OrderDate = value
				Me.SendPropertyChanged("OrderDate")
				Me.OnOrderDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubmittedBy", DbType:="NVarChar(100)")>  _
	Public Property SubmittedBy() As String
		Get
			Return Me._SubmittedBy
		End Get
		Set
			If (String.Equals(Me._SubmittedBy, value) = false) Then
				Me.OnSubmittedByChanging(value)
				Me.SendPropertyChanging
				Me._SubmittedBy = value
				Me.SendPropertyChanged("SubmittedBy")
				Me.OnSubmittedByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TotalPricePerAcre", DbType:="Decimal(12,4)")>  _
	Public Property TotalPricePerAcre() As System.Nullable(Of Decimal)
		Get
			Return Me._TotalPricePerAcre
		End Get
		Set
			If (Me._TotalPricePerAcre.Equals(value) = false) Then
				Me.OnTotalPricePerAcreChanging(value)
				Me.SendPropertyChanging
				Me._TotalPricePerAcre = value
				Me.SendPropertyChanged("TotalPricePerAcre")
				Me.OnTotalPricePerAcreChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderStatusId", DbType:="BigInt")>  _
	Public Property OrderStatusId() As System.Nullable(Of Long)
		Get
			Return Me._OrderStatusId
		End Get
		Set
			If (Me._OrderStatusId.Equals(value) = false) Then
				Me.OnOrderStatusIdChanging(value)
				Me.SendPropertyChanging
				Me._OrderStatusId = value
				Me.SendPropertyChanged("OrderStatusId")
				Me.OnOrderStatusIdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PriceList", DbType:="NVarChar(50)")>  _
	Public Property PriceList() As String
		Get
			Return Me._PriceList
		End Get
		Set
			If (String.Equals(Me._PriceList, value) = false) Then
				Me.OnPriceListChanging(value)
				Me.SendPropertyChanging
				Me._PriceList = value
				Me.SendPropertyChanged("PriceList")
				Me.OnPriceListChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="Order_OrderCustomerDetails", Storage:="_OrderCustomerDetails", ThisKey:="CustomerID", OtherKey:="CustomerId")>  _
	Public Property OrderCustomerDetails() As EntitySet(Of OrderCustomerDetails)
		Get
			Return Me._OrderCustomerDetails
		End Get
		Set
			Me._OrderCustomerDetails.Assign(value)
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="Order_OrderItem", Storage:="_OrderItems", ThisKey:="OrderID", OtherKey:="OrderID")>  _
	Public Property OrderItems() As EntitySet(Of OrderItem)
		Get
			Return Me._OrderItems
		End Get
		Set
			Me._OrderItems.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_OrderCustomerDetails(ByVal entity As OrderCustomerDetails)
		Me.SendPropertyChanging
		entity.[Order] = Me
	End Sub
	
	Private Sub detach_OrderCustomerDetails(ByVal entity As OrderCustomerDetails)
		Me.SendPropertyChanging
		entity.[Order] = Nothing
	End Sub
	
	Private Sub attach_OrderItems(ByVal entity As OrderItem)
		Me.SendPropertyChanging
		entity.[Order] = Me
	End Sub
	
	Private Sub detach_OrderItems(ByVal entity As OrderItem)
		Me.SendPropertyChanging
		entity.[Order] = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.OrderItems")>  _
Partial Public Class OrderItem
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _OrderItemID As Integer
	
	Private _ItemID As Integer
	
	Private _OrderID As Integer
	
	Private _PricePerAcre As System.Nullable(Of Decimal)
	
	Private _TotalPrice As System.Nullable(Of Decimal)
	
	Private _PLS_LBS_PerAcre As System.Nullable(Of Decimal)
	
	Private _PricePerPLSLB As System.Nullable(Of Decimal)
	
	Private _BulkLbs As System.Nullable(Of Decimal)
	
	Private _PLSLbs As System.Nullable(Of Decimal)
	
	Private _PLS_Percent As System.Nullable(Of Decimal)
	
	Private _OrderItemDetails As EntitySet(Of OrderItemDetail)
	
	Private _Order As EntityRef(Of [Order])
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnOrderItemIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnOrderItemIDChanged()
    End Sub
    Partial Private Sub OnItemIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnItemIDChanged()
    End Sub
    Partial Private Sub OnOrderIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnOrderIDChanged()
    End Sub
    Partial Private Sub OnPricePerAcreChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnPricePerAcreChanged()
    End Sub
    Partial Private Sub OnTotalPriceChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnTotalPriceChanged()
    End Sub
    Partial Private Sub OnPLS_LBS_PerAcreChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnPLS_LBS_PerAcreChanged()
    End Sub
    Partial Private Sub OnPricePerPLSLBChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnPricePerPLSLBChanged()
    End Sub
    Partial Private Sub OnBulkLbsChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnBulkLbsChanged()
    End Sub
    Partial Private Sub OnPLSLbsChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnPLSLbsChanged()
    End Sub
    Partial Private Sub OnPLS_PercentChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnPLS_PercentChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._OrderItemDetails = New EntitySet(Of OrderItemDetail)(AddressOf Me.attach_OrderItemDetails, AddressOf Me.detach_OrderItemDetails)
		Me._Order = CType(Nothing, EntityRef(Of [Order]))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderItemID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property OrderItemID() As Integer
		Get
			Return Me._OrderItemID
		End Get
		Set
			If ((Me._OrderItemID = value)  _
						= false) Then
				Me.OnOrderItemIDChanging(value)
				Me.SendPropertyChanging
				Me._OrderItemID = value
				Me.SendPropertyChanged("OrderItemID")
				Me.OnOrderItemIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ItemID", DbType:="Int NOT NULL")>  _
	Public Property ItemID() As Integer
		Get
			Return Me._ItemID
		End Get
		Set
			If ((Me._ItemID = value)  _
						= false) Then
				Me.OnItemIDChanging(value)
				Me.SendPropertyChanging
				Me._ItemID = value
				Me.SendPropertyChanged("ItemID")
				Me.OnItemIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderID", DbType:="Int NOT NULL")>  _
	Public Property OrderID() As Integer
		Get
			Return Me._OrderID
		End Get
		Set
			If ((Me._OrderID = value)  _
						= false) Then
				If Me._Order.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnOrderIDChanging(value)
				Me.SendPropertyChanging
				Me._OrderID = value
				Me.SendPropertyChanged("OrderID")
				Me.OnOrderIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PricePerAcre", DbType:="Decimal(12,4)")>  _
	Public Property PricePerAcre() As System.Nullable(Of Decimal)
		Get
			Return Me._PricePerAcre
		End Get
		Set
			If (Me._PricePerAcre.Equals(value) = false) Then
				Me.OnPricePerAcreChanging(value)
				Me.SendPropertyChanging
				Me._PricePerAcre = value
				Me.SendPropertyChanged("PricePerAcre")
				Me.OnPricePerAcreChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TotalPrice", DbType:="Decimal(12,4)")>  _
	Public Property TotalPrice() As System.Nullable(Of Decimal)
		Get
			Return Me._TotalPrice
		End Get
		Set
			If (Me._TotalPrice.Equals(value) = false) Then
				Me.OnTotalPriceChanging(value)
				Me.SendPropertyChanging
				Me._TotalPrice = value
				Me.SendPropertyChanged("TotalPrice")
				Me.OnTotalPriceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PLS_LBS_PerAcre", DbType:="Decimal(12,4)")>  _
	Public Property PLS_LBS_PerAcre() As System.Nullable(Of Decimal)
		Get
			Return Me._PLS_LBS_PerAcre
		End Get
		Set
			If (Me._PLS_LBS_PerAcre.Equals(value) = false) Then
				Me.OnPLS_LBS_PerAcreChanging(value)
				Me.SendPropertyChanging
				Me._PLS_LBS_PerAcre = value
				Me.SendPropertyChanged("PLS_LBS_PerAcre")
				Me.OnPLS_LBS_PerAcreChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PricePerPLSLB", DbType:="Decimal(12,4)")>  _
	Public Property PricePerPLSLB() As System.Nullable(Of Decimal)
		Get
			Return Me._PricePerPLSLB
		End Get
		Set
			If (Me._PricePerPLSLB.Equals(value) = false) Then
				Me.OnPricePerPLSLBChanging(value)
				Me.SendPropertyChanging
				Me._PricePerPLSLB = value
				Me.SendPropertyChanged("PricePerPLSLB")
				Me.OnPricePerPLSLBChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BulkLbs", DbType:="Decimal(12,4)")>  _
	Public Property BulkLbs() As System.Nullable(Of Decimal)
		Get
			Return Me._BulkLbs
		End Get
		Set
			If (Me._BulkLbs.Equals(value) = false) Then
				Me.OnBulkLbsChanging(value)
				Me.SendPropertyChanging
				Me._BulkLbs = value
				Me.SendPropertyChanged("BulkLbs")
				Me.OnBulkLbsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PLSLbs", DbType:="Decimal(12,4)")>  _
	Public Property PLSLbs() As System.Nullable(Of Decimal)
		Get
			Return Me._PLSLbs
		End Get
		Set
			If (Me._PLSLbs.Equals(value) = false) Then
				Me.OnPLSLbsChanging(value)
				Me.SendPropertyChanging
				Me._PLSLbs = value
				Me.SendPropertyChanged("PLSLbs")
				Me.OnPLSLbsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PLS_Percent", DbType:="Decimal(12,8)")>  _
	Public Property PLS_Percent() As System.Nullable(Of Decimal)
		Get
			Return Me._PLS_Percent
		End Get
		Set
			If (Me._PLS_Percent.Equals(value) = false) Then
				Me.OnPLS_PercentChanging(value)
				Me.SendPropertyChanging
				Me._PLS_Percent = value
				Me.SendPropertyChanged("PLS_Percent")
				Me.OnPLS_PercentChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="OrderItem_OrderItemDetail", Storage:="_OrderItemDetails", ThisKey:="ItemID", OtherKey:="ItemID")>  _
	Public Property OrderItemDetails() As EntitySet(Of OrderItemDetail)
		Get
			Return Me._OrderItemDetails
		End Get
		Set
			Me._OrderItemDetails.Assign(value)
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="Order_OrderItem", Storage:="_Order", ThisKey:="OrderID", OtherKey:="OrderID", IsForeignKey:=true)>  _
	Public Property [Order]() As [Order]
		Get
			Return Me._Order.Entity
		End Get
		Set
			Dim previousValue As [Order] = Me._Order.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._Order.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._Order.Entity = Nothing
					previousValue.OrderItems.Remove(Me)
				End If
				Me._Order.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.OrderItems.Add(Me)
					Me._OrderID = value.OrderID
				Else
					Me._OrderID = CType(Nothing, Integer)
				End If
				Me.SendPropertyChanged("[Order]")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_OrderItemDetails(ByVal entity As OrderItemDetail)
		Me.SendPropertyChanging
		entity.OrderItem = Me
	End Sub
	
	Private Sub detach_OrderItemDetails(ByVal entity As OrderItemDetail)
		Me.SendPropertyChanging
		entity.OrderItem = Nothing
	End Sub
End Class
