<?xml version="1.0" encoding="utf-8"?><Database Name="Seed" Class="OrderStatusDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.OrderStatus" Member="OrderStatus">
    <Type Name="OrderStatus">
      <Column Name="OrderStatusID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="OrderStatusName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>