'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Seed")>  _
Partial Public Class SeedReportsDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertSeedReport(instance As SeedReport)
    End Sub
  Partial Private Sub UpdateSeedReport(instance As SeedReport)
    End Sub
  Partial Private Sub DeleteSeedReport(instance As SeedReport)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.SeedGeneral.My.MySettings.Default.SeedConnectionString1, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property SeedReports() As System.Data.Linq.Table(Of SeedReport)
		Get
			Return Me.GetTable(Of SeedReport)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SeedReports")>  _
Partial Public Class SeedReport
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ReportFileName As String
	
	Private _FriendlyName As String
	
	Private _ReportID As Long
	
	Private _HasSubReports As System.Nullable(Of Boolean)
	
	Private _IsVisible As System.Nullable(Of Boolean)
	
	Private _SortOrder As System.Nullable(Of Integer)
	
	Private _IsLandscape As System.Nullable(Of Boolean)
	
	Private _AllowMultiple As System.Nullable(Of Boolean)
	
	Private _NeedsOrder As System.Nullable(Of Boolean)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnReportFileNameChanging(value As String)
    End Sub
    Partial Private Sub OnReportFileNameChanged()
    End Sub
    Partial Private Sub OnFriendlyNameChanging(value As String)
    End Sub
    Partial Private Sub OnFriendlyNameChanged()
    End Sub
    Partial Private Sub OnReportIDChanging(value As Long)
    End Sub
    Partial Private Sub OnReportIDChanged()
    End Sub
    Partial Private Sub OnHasSubReportsChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnHasSubReportsChanged()
    End Sub
    Partial Private Sub OnIsVisibleChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsVisibleChanged()
    End Sub
    Partial Private Sub OnSortOrderChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSortOrderChanged()
    End Sub
    Partial Private Sub OnIsLandscapeChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsLandscapeChanged()
    End Sub
    Partial Private Sub OnAllowMultipleChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnAllowMultipleChanged()
    End Sub
    Partial Private Sub OnNeedsOrderChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnNeedsOrderChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ReportFileName", DbType:="NVarChar(100)")>  _
	Public Property ReportFileName() As String
		Get
			Return Me._ReportFileName
		End Get
		Set
			If (String.Equals(Me._ReportFileName, value) = false) Then
				Me.OnReportFileNameChanging(value)
				Me.SendPropertyChanging
				Me._ReportFileName = value
				Me.SendPropertyChanged("ReportFileName")
				Me.OnReportFileNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FriendlyName", DbType:="NVarChar(100)")>  _
	Public Property FriendlyName() As String
		Get
			Return Me._FriendlyName
		End Get
		Set
			If (String.Equals(Me._FriendlyName, value) = false) Then
				Me.OnFriendlyNameChanging(value)
				Me.SendPropertyChanging
				Me._FriendlyName = value
				Me.SendPropertyChanged("FriendlyName")
				Me.OnFriendlyNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ReportID", DbType:="BigInt NOT NULL", IsPrimaryKey:=true)>  _
	Public Property ReportID() As Long
		Get
			Return Me._ReportID
		End Get
		Set
			If ((Me._ReportID = value)  _
						= false) Then
				Me.OnReportIDChanging(value)
				Me.SendPropertyChanging
				Me._ReportID = value
				Me.SendPropertyChanged("ReportID")
				Me.OnReportIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HasSubReports", DbType:="Bit")>  _
	Public Property HasSubReports() As System.Nullable(Of Boolean)
		Get
			Return Me._HasSubReports
		End Get
		Set
			If (Me._HasSubReports.Equals(value) = false) Then
				Me.OnHasSubReportsChanging(value)
				Me.SendPropertyChanging
				Me._HasSubReports = value
				Me.SendPropertyChanged("HasSubReports")
				Me.OnHasSubReportsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsVisible", DbType:="Bit")>  _
	Public Property IsVisible() As System.Nullable(Of Boolean)
		Get
			Return Me._IsVisible
		End Get
		Set
			If (Me._IsVisible.Equals(value) = false) Then
				Me.OnIsVisibleChanging(value)
				Me.SendPropertyChanging
				Me._IsVisible = value
				Me.SendPropertyChanged("IsVisible")
				Me.OnIsVisibleChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SortOrder", DbType:="Int")>  _
	Public Property SortOrder() As System.Nullable(Of Integer)
		Get
			Return Me._SortOrder
		End Get
		Set
			If (Me._SortOrder.Equals(value) = false) Then
				Me.OnSortOrderChanging(value)
				Me.SendPropertyChanging
				Me._SortOrder = value
				Me.SendPropertyChanged("SortOrder")
				Me.OnSortOrderChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsLandscape", DbType:="Bit")>  _
	Public Property IsLandscape() As System.Nullable(Of Boolean)
		Get
			Return Me._IsLandscape
		End Get
		Set
			If (Me._IsLandscape.Equals(value) = false) Then
				Me.OnIsLandscapeChanging(value)
				Me.SendPropertyChanging
				Me._IsLandscape = value
				Me.SendPropertyChanged("IsLandscape")
				Me.OnIsLandscapeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AllowMultiple", DbType:="Bit")>  _
	Public Property AllowMultiple() As System.Nullable(Of Boolean)
		Get
			Return Me._AllowMultiple
		End Get
		Set
			If (Me._AllowMultiple.Equals(value) = false) Then
				Me.OnAllowMultipleChanging(value)
				Me.SendPropertyChanging
				Me._AllowMultiple = value
				Me.SendPropertyChanged("AllowMultiple")
				Me.OnAllowMultipleChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NeedsOrder", DbType:="Bit")>  _
	Public Property NeedsOrder() As System.Nullable(Of Boolean)
		Get
			Return Me._NeedsOrder
		End Get
		Set
			If (Me._NeedsOrder.Equals(value) = false) Then
				Me.OnNeedsOrderChanging(value)
				Me.SendPropertyChanging
				Me._NeedsOrder = value
				Me.SendPropertyChanged("NeedsOrder")
				Me.OnNeedsOrderChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
